import argparse
import csv
import importlib
import json
import math
import os
import re
import sys
import traceback
from pathlib import Path

import numpy as np
from PIL import Image


CODE_DIR = Path(__file__).resolve().parent
if str(CODE_DIR) not in sys.path:
    sys.path.insert(0, str(CODE_DIR))


TEST_IMAGE_RE = re.compile(r"^test(?P<sample>\d+)-(?P<copy>\d+)\.png$")
PAIRWISE_METRICS = ("mse", "pcc", "ssim", "psm")


class EvaluationError(RuntimeError):
    pass


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate images generated by code/gen_eval_eeg.py. The script reads "
            "testX-Y.png files from a results/eval/<timestamp> directory and "
            "uses code/eval_metrics.py whenever possible."
        )
    )
    parser.add_argument("run_dir", type=Path, help="Directory containing testX-Y.png files.")
    parser.add_argument("--device", default="cuda", choices=["cuda", "cpu"], help="Device for PSM and class metrics.")
    parser.add_argument("--limit", "--limit-samples", dest="limit", type=int, default=None,
                        help="Evaluate only the first N samples. Omit it to evaluate all samples.")
    parser.add_argument("--skip-psm", action="store_true", help="Skip the author's PSM/LPIPS metric.")
    parser.add_argument("--skip-class", action="store_true", help="Skip the author's n-way top-k class metric.")
    parser.add_argument("--gt-index", type=int, default=0, help="Ground-truth image index. Default: 0.")
    parser.add_argument("--prediction-index", type=int, default=None,
                        help="Evaluate only one generated copy index, e.g. 1. Default: all generated indices.")
    parser.add_argument("--top-k", type=int, default=1, help="Top-k for the class metric. Default: 1.")
    parser.add_argument("--n-way", type=int, default=50, help="N-way setting for the class metric. Default: 50.")
    parser.add_argument("--num-trials", type=int, default=50,
                        help="Number of random trials for the class metric. Default: 50.")
    parser.add_argument("--output-prefix", default="author_eval", help="Prefix for CSV/JSON output files.")
    parser.add_argument("--metrics", default="mse,pcc,ssim,psm",
                        help="Comma-separated pair-wise metrics to run. Default: mse,pcc,ssim,psm.")
    args = parser.parse_args()

    if args.limit is not None and args.limit <= 0:
        parser.error("--limit must be a positive integer.")

    metrics = [name.strip().lower() for name in args.metrics.split(",") if name.strip()]
    unknown = sorted(set(metrics) - set(PAIRWISE_METRICS))
    if unknown:
        parser.error(f"Unknown --metrics values: {unknown}. Valid choices: {', '.join(PAIRWISE_METRICS)}.")
    if args.skip_psm:
        metrics = [name for name in metrics if name != "psm"]
    args.metrics = metrics
    return args


def debug(message):
    print(message, flush=True)


def load_author_eval_metrics():
    try:
        module = importlib.import_module("eval_metrics")
    except Exception as exc:
        debug("[WARN] Could not import code/eval_metrics.py.")
        debug(f"[WARN] Import error: {type(exc).__name__}: {exc}")
        debug("[WARN] MSE/PCC/SSIM will use a local fallback that matches the author's pair-wise logic.")
        return None

    patch_torchmetrics_accuracy(module)
    return module


def patch_torchmetrics_accuracy(author_eval_metrics):
    original_accuracy = getattr(author_eval_metrics, "accuracy", None)
    if original_accuracy is None:
        return

    def accuracy_compat(preds, target, top_k=1):
        try:
            return original_accuracy(preds, target, top_k=top_k)
        except TypeError:
            return original_accuracy(
                preds,
                target,
                task="multiclass",
                num_classes=preds.shape[-1],
                top_k=top_k,
            )

    author_eval_metrics.accuracy = accuracy_compat


def collect_images(run_dir):
    if not run_dir.exists():
        raise FileNotFoundError(f"run_dir does not exist: {run_dir}")
    if not run_dir.is_dir():
        raise NotADirectoryError(f"run_dir is not a directory: {run_dir}")

    grouped = {}
    ignored_pngs = []
    for path in sorted(run_dir.glob("*.png")):
        match = TEST_IMAGE_RE.match(path.name)
        if match is None:
            ignored_pngs.append(path.name)
            continue
        sample_id = int(match.group("sample"))
        copy_id = int(match.group("copy"))
        grouped.setdefault(sample_id, {})[copy_id] = path

    if not grouped:
        png_hint = f" Found PNG files that do not match testX-Y.png: {ignored_pngs[:10]}" if ignored_pngs else ""
        raise FileNotFoundError(
            f"No files matching testX-Y.png were found in {run_dir}.{png_hint}"
        )

    return dict(sorted(grouped.items()))


def select_samples(grouped, gt_index, prediction_index, limit):
    gt_sample_ids = [sample_id for sample_id, copies in grouped.items() if gt_index in copies]
    gt_missing = [sample_id for sample_id, copies in grouped.items() if gt_index not in copies]
    if not gt_sample_ids:
        examples = ", ".join(f"testX-{gt_index}.png" for _ in range(1))
        raise EvaluationError(
            f"No ground-truth images with gt-index={gt_index} were found. "
            f"Expected files like {examples} under the run_dir."
        )

    selected_ids = gt_sample_ids[:limit] if limit is not None else gt_sample_ids
    if not selected_ids:
        raise EvaluationError("No samples selected for evaluation.")

    if prediction_index is None:
        prediction_indices = sorted({
            copy_id
            for sample_id in selected_ids
            for copy_id in grouped[sample_id]
            if copy_id != gt_index
        })
    else:
        prediction_indices = [prediction_index]

    if not prediction_indices:
        raise EvaluationError(
            f"No generated images were found for selected samples. "
            f"Ground truth uses testX-{gt_index}.png, so generated files should be testX-Y.png with Y != {gt_index}."
        )

    return selected_ids, prediction_indices, gt_missing


def load_rgb(path):
    try:
        return np.asarray(Image.open(path).convert("RGB"), dtype=np.float32)
    except Exception as exc:
        raise EvaluationError(f"Failed to read image {path}: {type(exc).__name__}: {exc}") from exc


def stack_pairs(grouped, sample_ids, gt_index, pred_index):
    complete_ids = []
    missing_gt = []
    missing_pred = []
    gt_images = []
    pred_images = []

    for sample_id in sample_ids:
        copies = grouped.get(sample_id, {})
        gt_path = copies.get(gt_index)
        pred_path = copies.get(pred_index)
        if gt_path is None:
            missing_gt.append(sample_id)
            continue
        if pred_path is None:
            missing_pred.append(sample_id)
            continue

        gt = load_rgb(gt_path)
        pred = load_rgb(pred_path)
        if gt.shape != pred.shape:
            raise EvaluationError(
                f"Image shape mismatch for sample {sample_id}: "
                f"{gt_path.name} has shape {gt.shape}, {pred_path.name} has shape {pred.shape}."
            )
        complete_ids.append(sample_id)
        gt_images.append(gt)
        pred_images.append(pred)

    if missing_gt:
        raise EvaluationError(
            f"Missing ground-truth files for gt-index={gt_index}: "
            f"{[f'test{sample_id}-{gt_index}.png' for sample_id in missing_gt[:20]]}"
        )
    if missing_pred:
        raise EvaluationError(
            f"Missing generated files for prediction-index={pred_index} in {len(missing_pred)} selected samples. "
            f"First missing files: {[f'test{sample_id}-{pred_index}.png' for sample_id in missing_pred[:20]]}"
        )
    if not complete_ids:
        raise EvaluationError(
            f"No complete pairs found for gt-index={gt_index} and prediction-index={pred_index}."
        )

    return complete_ids, np.stack(pred_images), np.stack(gt_images)


def finite_mean(values):
    clean = []
    for value in values:
        value = float(value)
        if not math.isnan(value):
            clean.append(value)
    if not clean:
        return float("nan")
    return float(np.mean(clean))


def fallback_metric_value(pred, gt, metric_name):
    if metric_name == "mse":
        return float(np.square(pred - gt).mean())
    if metric_name == "pcc":
        pred_flat = pred.reshape(-1)
        gt_flat = gt.reshape(-1)
        if np.std(pred_flat) == 0 or np.std(gt_flat) == 0:
            return float("nan")
        return float(np.corrcoef(pred_flat, gt_flat)[0, 1])
    if metric_name == "ssim":
        from skimage.metrics import structural_similarity
        return float(structural_similarity(pred, gt, data_range=255, channel_axis=-1))
    raise NotImplementedError(metric_name)


def fallback_pairwise_scores(pred_images, gt_images, metric_name):
    if metric_name not in {"mse", "pcc", "ssim"}:
        raise EvaluationError(
            f"Metric '{metric_name}' requires code/eval_metrics.py and its optional dependencies."
        )

    larger_is_better = metric_name in {"pcc", "ssim"}
    scores = []
    for idx, pred in enumerate(pred_images):
        gt_score = fallback_metric_value(pred, gt_images[idx], metric_name)
        count = 0
        total = 0
        for comp_idx, comp in enumerate(gt_images):
            if comp_idx == idx:
                continue
            comp_score = fallback_metric_value(pred, comp, metric_name)
            if math.isnan(gt_score) or math.isnan(comp_score):
                continue
            if (gt_score > comp_score) if larger_is_better else (gt_score < comp_score):
                count += 1
            total += 1
        scores.append(count / total if total else float("nan"))
    return scores


def compute_pairwise(author_eval_metrics, pred_images, gt_images, metric_name):
    if author_eval_metrics is not None:
        return author_eval_metrics.get_similarity_metric(
            pred_images,
            gt_images,
            method="pair-wise",
            metric_name=metric_name,
        )
    return fallback_pairwise_scores(pred_images, gt_images, metric_name)


def compute_class(author_eval_metrics, pred_images, gt_images, args):
    if author_eval_metrics is None:
        raise EvaluationError("Class metric requires importing code/eval_metrics.py, but that import failed.")
    maybe_print_vit_cache_status()
    return author_eval_metrics.get_similarity_metric(
        pred_images,
        gt_images,
        method="class",
        metric_name=None,
        n_way=args.n_way,
        num_trials=args.num_trials,
        top_k=args.top_k,
        device=args.device,
    )


def maybe_print_vit_cache_status():
    try:
        import torch
        from torchvision.models import ViT_H_14_Weights
        weights = ViT_H_14_Weights.DEFAULT
        filename = os.path.basename(weights.url)
        cache_path = Path(torch.hub.get_dir()) / "checkpoints" / filename
        if cache_path.exists():
            debug(f"ViT-H-14 cache found: {cache_path}")
        else:
            debug(f"[WARN] ViT-H-14 cache not found at: {cache_path}")
            debug(f"[WARN] torchvision may try to download: {weights.url}")
    except Exception as exc:
        debug(f"[WARN] Could not check ViT-H-14 cache status: {type(exc).__name__}: {exc}")


def write_csv(path, rows):
    fieldnames = sorted({key for row in rows for key in row.keys()})
    preferred = ["prediction_index", "num_samples"]
    fieldnames = preferred + [name for name in fieldnames if name not in preferred]
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def json_ready(value):
    if isinstance(value, float) and math.isnan(value):
        return None
    if isinstance(value, Path):
        return str(value)
    return value


def main():
    args = parse_args()
    run_dir = args.run_dir.resolve()

    debug(f"run_dir: {run_dir}")
    grouped = collect_images(run_dir)

    all_image_count = sum(len(copies) for copies in grouped.values())
    gt_count = sum(1 for copies in grouped.values() if args.gt_index in copies)
    generated_count = sum(
        1 for copies in grouped.values() for copy_id in copies if copy_id != args.gt_index
    )

    selected_sample_ids, prediction_indices, gt_missing = select_samples(
        grouped,
        gt_index=args.gt_index,
        prediction_index=args.prediction_index,
        limit=args.limit,
    )

    debug(f"found total test images: {all_image_count}")
    debug(f"found generated images: {generated_count}")
    debug(f"found ground truth images: {gt_count}")
    if gt_missing:
        debug(f"[WARN] samples missing ground truth testX-{args.gt_index}.png: {gt_missing[:20]}")
    debug(f"actual samples selected for evaluation: {len(selected_sample_ids)}")
    if len(selected_sample_ids) < 2 and args.metrics:
        debug("[WARN] Pair-wise ranking metrics need at least 2 actual samples, so these metrics will be nan.")
    debug(f"selected sample ids: {selected_sample_ids[:20]}{' ...' if len(selected_sample_ids) > 20 else ''}")
    debug(f"prediction indices selected: {prediction_indices}")
    debug(f"pair-wise metrics selected: {args.metrics}")
    debug(f"class metric enabled: {not args.skip_class}")

    debug("importing code/eval_metrics.py ...")
    author_eval_metrics = load_author_eval_metrics()
    if author_eval_metrics is not None:
        debug("imported code/eval_metrics.py successfully.")

    rows = []
    metric_errors = {}

    for pred_index in prediction_indices:
        debug("")
        debug(f"loading aligned images for prediction-index={pred_index} ...")
        sample_ids, pred_images, gt_images = stack_pairs(
            grouped,
            selected_sample_ids,
            gt_index=args.gt_index,
            pred_index=pred_index,
        )
        debug(f"actual paired samples for prediction-index={pred_index}: {len(sample_ids)}")

        row = {
            "prediction_index": pred_index,
            "num_samples": len(sample_ids),
        }

        for metric_name in args.metrics:
            debug(f"start metric: pair-wise_{metric_name}")
            key = f"pair-wise_{metric_name}"
            try:
                scores = compute_pairwise(author_eval_metrics, pred_images, gt_images, metric_name)
                row[key] = finite_mean(scores)
                debug(f"result {key}: {row[key]:.6f}")
            except Exception as exc:
                row[key] = float("nan")
                metric_errors[f"{key}/prediction-{pred_index}"] = f"{type(exc).__name__}: {exc}"
                debug(f"[WARN] metric failed: {key}: {type(exc).__name__}: {exc}")
                if metric_name in {"mse", "pcc", "ssim"} and author_eval_metrics is not None:
                    debug(f"[WARN] retrying {key} with local fallback ...")
                    try:
                        scores = fallback_pairwise_scores(pred_images, gt_images, metric_name)
                        row[key] = finite_mean(scores)
                        debug(f"result {key} using fallback: {row[key]:.6f}")
                    except Exception as fallback_exc:
                        metric_errors[f"{key}/prediction-{pred_index}/fallback"] = (
                            f"{type(fallback_exc).__name__}: {fallback_exc}"
                        )
                        debug(traceback.format_exc())

        if not args.skip_class:
            class_key = f"top-{args.top_k}-class"
            debug(f"start metric: {class_key}")
            try:
                scores = compute_class(author_eval_metrics, pred_images, gt_images, args)
                row[class_key] = finite_mean(scores)
                debug(f"result {class_key}: {row[class_key]:.6f}")
            except Exception as exc:
                row[class_key] = float("nan")
                metric_errors[f"{class_key}/prediction-{pred_index}"] = f"{type(exc).__name__}: {exc}"
                debug(f"[WARN] metric failed: {class_key}: {type(exc).__name__}: {exc}")
                debug("[WARN] MSE/PCC/SSIM results are still valid. Use --skip-class to omit this metric.")

        rows.append(row)

    summary = {
        "run_dir": str(run_dir),
        "gt_index": args.gt_index,
        "prediction_index": args.prediction_index,
        "prediction_indices": prediction_indices,
        "limit": args.limit,
        "num_total_test_images": all_image_count,
        "num_generated_images": generated_count,
        "num_ground_truth_images": gt_count,
        "num_selected_samples": len(selected_sample_ids),
        "selected_sample_ids": selected_sample_ids,
        "pairwise_metrics": args.metrics,
        "skip_psm": args.skip_psm,
        "skip_class": args.skip_class,
        "device": args.device,
        "n_way": args.n_way,
        "top_k": args.top_k,
        "num_trials": args.num_trials,
        "per_prediction": rows,
        "metric_errors": metric_errors,
    }

    for metric_name in args.metrics:
        key = f"pair-wise_{metric_name}"
        summary[key] = finite_mean([row.get(key, float("nan")) for row in rows])

    class_key = f"top-{args.top_k}-class"
    if not args.skip_class:
        class_values = [row.get(class_key, float("nan")) for row in rows]
        summary[class_key] = finite_mean(class_values)
        finite_class_values = [value for value in class_values if not math.isnan(value)]
        summary[f"{class_key} (max)"] = float(np.max(finite_class_values)) if finite_class_values else float("nan")

    csv_path = run_dir / f"{args.output_prefix}_per_prediction.csv"
    json_path = run_dir / f"{args.output_prefix}_summary.json"
    write_csv(csv_path, rows)
    json_path.write_text(json.dumps(summary, indent=2, default=json_ready))

    debug("")
    debug("final metric results:")
    for metric_name in args.metrics:
        key = f"pair-wise_{metric_name}"
        value = summary[key]
        debug(f"  {key}: {value:.6f}" if not math.isnan(value) else f"  {key}: nan")
    if not args.skip_class:
        value = summary[class_key]
        max_value = summary[f"{class_key} (max)"]
        debug(f"  {class_key}: {value:.6f}" if not math.isnan(value) else f"  {class_key}: nan")
        debug(
            f"  {class_key} (max): {max_value:.6f}"
            if not math.isnan(max_value)
            else f"  {class_key} (max): nan"
        )
    if metric_errors:
        debug("")
        debug("metric errors:")
        for key, value in metric_errors.items():
            debug(f"  {key}: {value}")
    debug("")
    debug(f"saved CSV: {csv_path}")
    debug(f"saved JSON: {json_path}")


if __name__ == "__main__":
    main()
